### PR TITLE
Apple and orange problem: C# solution

### PR DESCRIPTION
**Pull request by rasik210**
Added a new C# based solution for apple and orange problem.

### CODE REVIEW

**Comment by RyanFehr** [comment]
The java solution to this problem reads the input within the for loop so that all of the apple/orange array does not have to be stored in memory. The current solution in C# is using O(n) memory, so it needs to be reduced to O(1) or the header needs to be updated to match the space complexity.

**Comment by rasik210** [comment]
Your observation is absolutely correct @RyanFehr . But unfortunately, C# doesn't have any equivalent of Scanner class in java which can read whitespace-delimited tokens. So I've no option but to read the space delimited input as a string, split them and store them in an array for processing. 

So this limitation is attributed to the fact that I've to submit this program on HackerRank and get the input setup by their existing infrastructure. If someone runs my program manually and gives input by hand then of course I will not need the array storage.

This is the reason why I still ignored the space complexity taken up by that array and mentioned it as O(1) in my thoughts section. C# language's shortcoming got exposed because of Hackerrank's input provision infrastructure :smile: .

I can still go ahead and implement a custom Scanner class in C# as well as mentioned in [this](https://stackoverflow.com/q/722270/465053) SO post but I believe it will be over engineering just for aligning my solution to HackerRank's infrastructure. If hackerrank would have been giving all inputs on separate lines then it would have been straight forward thing for me as I'm using C# language.

I hope you will be able to merge my pull request now. Please let me know if you still have any concerns around it.

**Comment by RyanFehr** [comment]
@rasik210 I am going to go ahead an update the header to point out the shortcoming in C#'s console parsing and then go ahead merge.

**Comment by RyanFehr** [comment]
@rasik210 I think I am going to go ahead an update the header to point out the shortcoming in C#'s

**Comment by rasik210** [comment]
Alright. This looks good. Going forward I'll take care of this from my side. I'll be mentioning the actual complexity in thoughts section and not an assumed complexity based on any limitation. I will also mention the reason if my solution is not matching optimal complexity due to language or environmental constraints. Thanks for making the edits from your end.

**Pull request merged**
