### PR TITLE
 Chocolate feast problem: C# solution

### PR DESCRIPTION
**Pull request by rasik210**
Added a new solution for chocolate feast problem using C# programming language. Also corrected the time complexity for this problem in readme.md file.

### CODE REVIEW

**Comment by rasik210** [comment]
@RyanFehr I've changed the time complexity of this problem in readme file to log(n) base m. Please review it. I think we should be mentioning the time complexity w.r.t. algorithm involved in Bobby's each trip to the store. Each trip to the store is just like one test case which runs time and again as he visits the store.

I've a while loop in my core algorithm so it appears that time complexity should be of order O(n). But here is how I look at it.

Effectively we've to process the total number of wrappers obtained initially in the first purchase using the while loop. Now, the number of wrappers gets reduced to n/m in each iteration of the while loop. So my conclusion is that the time complexity of this problem should be O(log(n) base m.

Please share your thoughts on the same.

**Comment by RyanFehr** [comment]
From looking back over the problem, it is the case that there is logarithmic reduction of the number of wrappers each time and its' base is m. Please include an explanation of the runtime "... the number of wrappers gets reduced to n/m in each iteration of the while loop. So my conclusion is that the time complexity of this problem should be O(log(n) base m." in the Header for your solution file.

**Comment by rasik210** [comment]
I've added more details in the notes section for this problem in readme file. Kindly review and provide feedback.

**Comment by rasik210** [comment]
Ohh. Ok. I thought you were asking me to fix the notes section in readme file. Thank you for updating the comments in the solution file.

**Pull request merged**
