### PR TITLE
 Counting sort 2 problem:C# solution.

### PR DESCRIPTION
**Pull request by rasik210**
Added a new solution for counting sort 2 problem using C# programming language.

### CODE REVIEW

**Comment by rasik210** [comment]
Hi @RyanFehr 

I've modified both the optimal time and space complexities in readme.  Reason for the same is as below:

- Time Complexity: There are two for loops which run n times each one after the other. Since the loops aren't nested so efficiency will still be of order n. The third for loop which runs a constant 100 number of times can also be ignored.

- Space Complexity: We require an additional array of size n to store the sorted output array. We also require an array of size 100 to store the frequency of number range from 0 to 99.  If we look at the constraints in the question then this array of fixed size 100 can be ignored.

The constraints in the problem are as below:

0 <= n < 1000000
0 <= x < 100

Please evaluate my feedback.

**Comment by RyanFehr** [comment]
Addressed here #126

**Comment by rasik210** [comment]
I considered your comment that you've mentioned in pull request #126 . I reviewed my solution again keeping your perspective in mind then I realized that we should change the space complexity for this problem in readme. It can't be O(k). We are storing the sorted array elements in a new array of size n. So space complexity should be O(n+k) instead. For time complexity, I'm in agreement with you. I've restored the original time complexity for this problem in readme but have changed the space complexity to O(n+k). Please let me know your thoughts on this. If you find it ok then you can merge the modified files in the pull request else we can discuss more about it.

**Comment by RyanFehr** [comment]
I agree

**Pull request merged**
