### PR TITLE
Adding Python solution to Journey to Moon.

### PR DESCRIPTION
**Pull request by capitan-jack**
Adding One solution. Was not able to find python solutions, the description says there are.
Looking for feedback on if the style/formatting suits the repo?
Would like to add more as i solve more.

### CODE REVIEW

**Comment by RyanFehr** [comment]
As far as formatting goes, before this pull request can be merged, you will need to add a header block of the following format:

```Python
'''
Problem: HackerRank.urlToProblem.com
Python Version#

Thoughts: A description of your approach to the problem

Time Complexity:  In big-O format
Space Complexity: In big-O format
'''
```

Also be sure to add a link to your solution on the readme, below the link to the Java solution.

**Comment by RyanFehr** [comment]
Here is a recent solution commit you can use as a reference: [example](https://github.com/RyanFehr/HackerRank/blob/master/Algorithms/Sorting/Marc's%20Cakewalk/Solution.java)

**Comment by capitan-jack** [comment]
@RyanFehr Made changes. Please review. And let me know of required changes.

**Comment by RyanFehr** [comment]
You will need to pull the most recent readme before adding any proposed changes. I had already added a Journey to the moon solution in Java, but it was listed wrong, so now it should be listed correctly. All you need to do is add the [Python]() link in the same column as the Java solution. For the url, use the location you are committing the solution to, which is _./Algorithms/Graph%20Theory/Journey%20to%20the%20Moon_  Also please write you time complexity in the same form that the editorial uses. In this specific case, it would be O(N + I)

**Comment by capitan-jack** [comment]
@RyanFehr I made the small changes. Will probably be straight forward from next pr. 

Just curious, isn't O(N + I) what it will take for DFS. 
All the building up the graph is part of the solution and therefore it is actually O(N*I)  in worst case(all astronauts being in same country and input relations coming in sequentially)?

This procedure from your code:
'''Java
for(int q = 0; q < I; q++)
        {
            int parent = input.nextInt();
            int child = input.nextInt();
            
            
            astronauts[parent] = (astronauts[parent] == -1) ? parent : astronauts[parent];
            astronauts[child] = (astronauts[child] == -1) ? child : astronauts[child];
             
            //Joining two graphs
            int oldRep = astronauts[child];
            astronauts[child] = astronauts[parent];

            //Updates pointers when combining two graphs with different representatives
            for(int qq = 0; qq < N; qq++)
            {
                if(astronauts[qq] == oldRep)
                {
                    astronauts[qq] = astronauts[parent];
                }
            }
        }
'''

**Comment by RyanFehr** [comment]
@capitan-jack Yes you are correct _(this is a old version of the problem, I will be uploading the newer solution soon)_ this solution will take O(I) time to read in all the pairs and then each Ith iteration it will take O(N) to iterate over the current disjoint sets. Thus the TC of the solution is O(N*I)

**Pull request merged**
