### PR TITLE
solution for deleting the node in linked list 

### PR DESCRIPTION
**Pull request by PalashLalwani**
Delete a Node from linked list solution

### CODE REVIEW

**Comment by rasik210** [comment]
Hi @PalashLalwani few quick things for your pull request to get accepted:

- readme.md file should reflect the details of your newly added solution.
- the soluition file (solution.cpp) should have a thoughts section where you mention the basic algorithmic steps which you followed to solve the problem.

Hope this helps you improvise your pull request to bring it to the norms setup for this repository.

**Comment by PalashLalwani** [comment]
Hi @rasik210 I updated it now you can review and thanks for your quick response.

**Comment by RyanFehr** [comment]
@PalashLalwani I have updated solution to have a properly formatted header. Use this as a example for any future pull requests you make. Congrats on your first pull request!

**Comment by PalashLalwani** [comment]
thank you @RyanFehr

**Pull request merged**
